import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark sm:pt-2 bg-[url('/bg.jpg')] bg-center bg-cover bg-primary/30 bg-blend-multiply text-foreground"
      // style={{ backgroundImage: `url("${image}")` }}
    >
      <body className="antialiased">
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
