import Header from "../components/header";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark sm:pt-2 bg-[url('/bg.jpg')] bg-center bg-cover bg-primary/30 bg-blend-multiply text-foreground"
      // style={{ backgroundImage: `url("${image}")` }}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sm:px-2 max-w-md flex justify-center flex-col items-center mx-auto overflow-x-hidden pb-8 border-border shadow rounded-md bg-background">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
